on:
  schedule:
    - cron:  '15 */1 * * *'

jobs:
  update-softwares:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8 ğŸ
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies ğŸ“¦
      run: |
        pip install -r cloud-data/requirements.txt
    - run: python -m cloud-data.importer
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'ğŸ¤– Update softwares'
        add: 'softwares/*'